image:
    path:     /
    defaults: { _controller: "angularjsBundle:ProductImage:index" }

image_show:
    path:     /{id}/show
    defaults: { _controller: "angularjsBundle:ProductImage:show" }

image_new:
    path:     /new
    defaults: { _controller: "angularjsBundle:ProductImage:new" }

image_create:
    path:     /create
    defaults: { _controller: "angularjsBundle:ProductImage:create" }
    methods:  POST

image_delete:
    path:     /{id}/delete
    defaults: { _controller: "angularjsBundle:ProductImage:delete" }
    methods:  [POST, DELETE]
