angularjs_review:
    resource: "@angularjsBundle/Resources/config/routing/review.yml"
    prefix:   /review

angularjs_product:
    resource: "@angularjsBundle/Resources/config/routing/product.yml"
    prefix:   /product

angularjs_homepagetmp:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'angularjsBundle:Default:index.html.twig'

angularjs_homepage:
    path:     /hello/{name}
    defaults: { _controller: angularjsBundle:Default:index }
